### ISSUE TITLE
Setup script fails for repositories cloned with SSH credentials

### ISSUE THREAD

**Issue by YannickMeeus** [pterm/cli-template#17]
Remotes for repositories cloned with SSH credentials have a slightly different format:

`git@github.com:organisation/cli.git`

This means that in the setup script, matching on "https://github.com/" isn't enough. Ideally, you would want to match on either https://github.com/ or git@github.com.

**Comment by MarvinJWendt** [comment]
The setup script is not meant to be run locally. When you click `Use this template` a new repository will be created and the setup script will automatically run via GitHub Actions and delete itself. By the time you clone the repository, the setup script should no longer exist :)

But thanks for the heads-up!

**Comment by YannickMeeus** [comment]
Riiiight, that did *not* happen for me, but I'll try that again. Worst case scenario it still doesn't work but at least I'll have repro steps for you. Best case scenario it all works out 😀

**Comment by MarvinJWendt** [comment]
Glad that it works now 😄 Let me know if you find anything else 👍
